version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:24.4.1

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Build Application
          command: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
